#!/usr/bin/env ruby
# frozen_string_literal: true

require "pathname"
bin_file = Pathname.new(__FILE__).realpath
$:.unshift File.expand_path("../../lib", bin_file)

require "lutaml"
require "lutaml/cli"

Lutaml::CLI.start(ARGV)
