name: ubuntu

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - .github/workflows/macos.yml
      - .github/workflows/windows.yml

jobs:
  test-linux:
    name: Test on Ruby ${{ matrix.ruby }} Ubuntu
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.0', '3.1' ]
        experimental: [false]
        include:
          - ruby: '3.2'
            experimental: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install GraphViz
        run: sudo apt-get install graphviz
      - name: Run specs
        run: |
          bundle exec rake
